import http from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('./public/',import.meta.url));
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.woff2':'font/woff2'};
const send=(res,status,body,headers={})=>{res.writeHead(status,{'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin',...headers});res.end(body);};
const json=(res,status,data)=>send(res,status,JSON.stringify(data),{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});
export async function tourism(path,params,key=process.env.TOUR_API_KEY){
 if(!key)return {status:503,data:{live:false,code:'NOT_CONFIGURED'}};
 const base=process.env.TOUR_API_BASE||'https://apis.data.go.kr/B551011/KorService2';
 const url=new URL(`${base.replace(/\/$/,'')}/${path}`);
 if(url.protocol!=='https:'||url.hostname!=='apis.data.go.kr')return {status:503,data:{live:false,code:'INVALID_API_BASE'}};
 let decoded=key;try{decoded=decodeURIComponent(key);}catch{}
 Object.entries({serviceKey:decoded,MobileOS:'ETC',MobileApp:'HwanseungLog',_type:'json',numOfRows:24,pageNo:1,...params}).forEach(([k,v])=>url.searchParams.set(k,String(v)));
 try{const response=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error();const data=await response.json();if(data.response?.header?.resultCode!=='0000'&&data.response?.header?.resultCode!=='00')throw Error();const raw=data.response?.body?.items?.item||[],items=Array.isArray(raw)?raw:[raw];return {status:200,data:{live:true,items,fetchedAt:new Date().toISOString(),source:'ⓒ한국관광공사'}};}catch{return {status:502,data:{live:false,code:'UPSTREAM_UNAVAILABLE'}};}
}
export function normalizePlace(p){const types={'12':'nature','14':'culture','15':'culture','28':'rest','38':'shopping','39':'food'};const image=/^https?:\/\//.test(p.firstimage||'')?p.firstimage.replace(/^http:/,'https:'):null;return {id:`kto-${p.contentid}`,contentid:String(p.contentid),name:String(p.title||''),en:String(p.title||''),category:types[p.contenttypeid]||'culture',region:p.areacode==='1'?'seoul':'incheon',lat:+p.mapy,lng:+p.mapx,live:true,indoor:false,image,liveImage:image,address:String(p.addr1||''),tags:['한국관광공사'],tagsEn:['Korea Tourism Organization'],sub:'한국관광공사에서 불러온 장소',subEn:'From Korea Tourism Organization',source:'https://english.visitkorea.or.kr/'};}
export const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(!['GET','HEAD'].includes(req.method))return json(res,405,{error:'Method not allowed'});if(url.pathname==='/api/status')return json(res,200,{tourismConfigured:!!process.env.TOUR_API_KEY});if(url.pathname==='/api/places'){if(!process.env.TOUR_API_KEY)return json(res,503,{live:false,code:'NOT_CONFIGURED'});const keywords=['경복궁','송도 센트럴파크','국립중앙박물관','인사동','국립세계문자박물관','인천 차이나타운','서울식물원','씨사이드파크'];const results=await Promise.all(keywords.map(keyword=>tourism('searchKeyword2',{keyword,numOfRows:3})));const ok=results.filter(r=>r.data.live);if(!ok.length)return json(res,502,{live:false,code:'UPSTREAM_UNAVAILABLE'});return json(res,200,{live:true,partial:ok.length<keywords.length,places:ok.flatMap(r=>r.data.items.map(normalizePlace)),fetchedAt:new Date().toISOString(),source:'ⓒ한국관광공사'});}if(url.pathname==='/api/detail'){const id=url.searchParams.get('id');if(!/^\d{1,12}$/.test(id||''))return json(res,400,{error:'Invalid content id'});const result=await tourism('detailCommon2',{contentId:id});return json(res,result.status,result.data);}if(url.pathname.startsWith('/api/'))return json(res,404,{error:'Not found'});const pathname=decodeURIComponent(url.pathname),file=resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root.endsWith(sep)?root:root+sep))return send(res,403,'Forbidden');const info=await stat(file);if(!info.isFile())return send(res,404,'Not found');const content=req.method==='HEAD'?null:await readFile(file);return send(res,200,content,{'Content-Type':MIME[extname(file)]||'application/octet-stream','Cache-Control':file.endsWith('sw.js')||file.endsWith('.html')?'no-cache':'public, max-age=300'});}catch(err){send(res,err.code==='ENOENT'?404:500,err.code==='ENOENT'?'Not found':'Request failed');}});
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const port=Number(process.env.PORT)||4173,host=process.env.HOST||'127.0.0.1';server.listen(port,host,()=>console.log(`Hwanseung Log ready: http://${host}:${port}`));}
